In [2]:
import numpy as np
from matplotlib.pyplot import imshow
%matplotlib inline

In [3]:
import h5py
import pandas as pd

In [4]:
vgg_cnn_s = np.load('vgg_cnn_s')

In [27]:
pd.DataFrame(vgg_cnn_s).head()

0 
 1 
 
 
 
 
 0 
 [[[[ 0.00694627 0.02646671 0.05854246 0.070... 
 [-1.82763, -0.886888, -1.12296, -1.38647, -0.8... 
 
 
 1 
 [[[[ 0.01162354 0.00300351 0.00242298 0.005... 
 [-0.0133935, 0.144076, -0.0797717, -0.0408563,... 
 
 
 2 
 [[[[-0.01205447 -0.01284794 -0.00854727], [-0.... 
 [0.0338069, -0.0286629, 0.196591, -0.13316, -0... 
 
 
 3 
 [[[[-0.01593209 -0.00740766 -0.00531611], [-0.... 
 [-0.342225, -0.0572309, -0.0629671, 0.383994, ... 
 
 
 4 
 [[[[-0.00664671 0.0014371 -0.00600124], [-0.... 
 [0.209937, 0.757988, 0.0250057, 0.957419, 0.00...

In [9]:
print vgg_cnn_s[0][0].shape, vgg_cnn_s[0][1].shape
print vgg_cnn_s[1][0].shape, vgg_cnn_s[1][1].shape
print vgg_cnn_s[2][0].shape, vgg_cnn_s[2][1].shape
print vgg_cnn_s[3][0].shape, vgg_cnn_s[3][1].shape
print vgg_cnn_s[4][0].shape, vgg_cnn_s[4][1].shape

(96, 3, 7, 7) (96,)
(256, 96, 5, 5) (256,)
(512, 256, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)


In [22]:
f = h5py.File('weights', 'r+')

In [23]:
f

<HDF5 file "weights" (mode r+)>

In [13]:
f.keys()

[u'layer_0',
 u'layer_1',
 u'layer_10',
 u'layer_11',
 u'layer_12',
 u'layer_13',
 u'layer_14',
 u'layer_15',
 u'layer_16',
 u'layer_17',
 u'layer_18',
 u'layer_19',
 u'layer_2',
 u'layer_20',
 u'layer_21',
 u'layer_22',
 u'layer_3',
 u'layer_4',
 u'layer_5',
 u'layer_6',
 u'layer_7',
 u'layer_8',
 u'layer_9']

In [15]:
f['layer_0'].name

u'/layer_0'

In [28]:
def print_structure(weight_file_path):
    """
    Prints out the structure of HDF5 file.

    Args:
      weight_file_path (str) : Path to the file to analyze
    """
    f = h5py.File(weight_file_path)
    try:
        if len(f.attrs.items()):
            print("{} contains: ".format(weight_file_path))
            print("Root attributes:")
        for key, value in f.attrs.items():
            print("  {}: {}".format(key, value))

        if len(f.items())==0:
            return 

        for layer, g in f.items():
            print("  {}".format(layer))
            print("    Attributes:")
            for key, value in g.attrs.items():
                print("      {}: {}".format(key, value))

            print("    Dataset:")
            for p_name in g.keys():
                param = g[p_name]
                print("      {}: {}".format(p_name, param.shape))
    finally:
        f.close()

In [26]:
def change_weights(weight_file_path, new_weights):
    f = h5py.File(weight_file_path)
    try:
        conv1 = f['layer_0']
        conv1['param_0'][...] = new_weights[0][0]
        conv1['param_1'][...] = new_weights[0][1]

        conv2 = f['layer_4']
        conv2['param_0'][...] = new_weights[1][0]
        conv2['param_1'][...] = new_weights[1][1]
        
        conv3 = f['layer_8']
        conv3['param_0'][...] = new_weights[2][0]
        conv3['param_1'][...] = new_weights[2][1]
        
        conv4 = f['layer_11']
        conv4['param_0'][...] = new_weights[3][0]
        conv4['param_1'][...] = new_weights[3][1]
        
        conv5 = f['layer_14']
        conv5['param_0'][...] = new_weights[4][0]
        conv5['param_1'][...] = new_weights[4][1]
    finally:
        f.close()

In [16]:
print f['layer_0'].get('param_0')

<HDF5 dataset "param_0": shape (96, 3, 7, 7), type "<f4">


In [18]:
asdf = f['layer_0'].get('param_0')

In [20]:
asdf[0]

array([[[ 0.02548014, -0.06538861,  0.03427604, -0.13627921, -0.04770178,
         -0.07539975, -0.12781651],
        [ 0.13489287,  0.08771172,  0.09096535, -0.13301775,  0.01225658,
          0.0806352 , -0.11605887],
        [-0.01556606, -0.08722959, -0.01264033, -0.03602605,  0.10978924,
         -0.09944959,  0.09035392],
        [-0.13011971,  0.07116457,  0.04754036, -0.10533587, -0.1276117 ,
         -0.1295224 ,  0.07363286],
        [-0.08034378, -0.13521312, -0.03021518, -0.06360974, -0.13557921,
          0.09752652, -0.02517726],
        [ 0.1242402 ,  0.01471879, -0.06720894, -0.06977405,  0.01169972,
         -0.10978332, -0.10963474],
        [ 0.10048558,  0.15640958,  0.12675501,  0.15533942,  0.15712398,
          0.12677784, -0.07439639]],

       [[-0.02161234, -0.10741585, -0.01408091, -0.13715145, -0.02592061,
          0.14533307, -0.11617971],
        [-0.08179731,  0.10103124, -0.08962483,  0.04237138, -0.00033962,
         -0.14067787, -0.0243728 ],
        

In [24]:
f['layer_0']['param_0'][...] = vgg_cnn_s[0][0]

In [25]:
f['layer_0'].get('param_0')[0]

array([[[ 0.00694627,  0.02646671,  0.05854246,  0.07002522,  0.05759254,
          0.03870812,  0.02337969],
        [ 0.08435953,  0.09220244,  0.10526367,  0.08194241,  0.03989906,
          0.00606399, -0.03152299],
        [ 0.06690404,  0.03335963,  0.01511758, -0.02870195, -0.06920688,
         -0.07811891, -0.08331555],
        [-0.02874666, -0.07674399, -0.11440271, -0.13730878, -0.13998373,
         -0.12641636, -0.10048065],
        [-0.06586082, -0.08039068, -0.09174092, -0.07055084, -0.0390115 ,
         -0.02588682, -0.00479862],
        [-0.03722067, -0.01418383,  0.0072077 ,  0.04982315,  0.08338538,
          0.06537562,  0.05121973],
        [ 0.04100299,  0.06384245,  0.07978272,  0.08332521,  0.082433  ,
          0.03156103,  0.01439718]],

       [[ 0.03847783,  0.07092094,  0.0959575 ,  0.11260303,  0.08716433,
          0.06934885,  0.03955302],
        [ 0.1137189 ,  0.12945727,  0.12917131,  0.10784075,  0.04773989,
          0.01424819, -0.03682533],
        

In [27]:
vgg_cnn_s[0][0][0]

array([[[ 0.00694627,  0.02646671,  0.05854246,  0.07002522,  0.05759254,
          0.03870812,  0.02337969],
        [ 0.08435953,  0.09220244,  0.10526367,  0.08194241,  0.03989906,
          0.00606399, -0.03152299],
        [ 0.06690404,  0.03335963,  0.01511758, -0.02870195, -0.06920688,
         -0.07811891, -0.08331555],
        [-0.02874666, -0.07674399, -0.11440271, -0.13730878, -0.13998373,
         -0.12641636, -0.10048065],
        [-0.06586082, -0.08039068, -0.09174092, -0.07055084, -0.0390115 ,
         -0.02588682, -0.00479862],
        [-0.03722067, -0.01418383,  0.0072077 ,  0.04982315,  0.08338538,
          0.06537562,  0.05121973],
        [ 0.04100299,  0.06384245,  0.07978272,  0.08332521,  0.082433  ,
          0.03156103,  0.01439718]],

       [[ 0.03847783,  0.07092094,  0.0959575 ,  0.11260303,  0.08716433,
          0.06934885,  0.03955302],
        [ 0.1137189 ,  0.12945727,  0.12917131,  0.10784075,  0.04773989,
          0.01424819, -0.03682533],
        

In [18]:
change_weights('weights','')

weights contains: 
Root attributes:
  nb_layers: 23
  layer_0
    Attributes:
      nb_params: 2
    Dataset:
      param_0: (96, 3, 7, 7)
      param_1: (96,)
  layer_1
    Attributes:
      nb_params: 0
    Dataset:
  layer_10
    Attributes:
      nb_params: 0
    Dataset:
  layer_11
    Attributes:
      nb_params: 2
    Dataset:
      param_0: (512, 512, 3, 3)
      param_1: (512,)
  layer_12
    Attributes:
      nb_params: 0
    Dataset:
  layer_13
    Attributes:
      nb_params: 0
    Dataset:
  layer_14
    Attributes:
      nb_params: 2
    Dataset:
      param_0: (512, 512, 3, 3)
      param_1: (512,)
  layer_15
    Attributes:
      nb_params: 0
    Dataset:
  layer_16
    Attributes:
      nb_params: 0
    Dataset:
  layer_17
    Attributes:
      nb_params: 0
    Dataset:
  layer_18
    Attributes:
      nb_params: 2
    Dataset:
      param_0: (50688, 512)
      param_1: (512,)
  layer_19
    Attributes:
      nb_params: 0
    Dataset:
  layer_2
    Attributes:
      nb

In [28]:
import datetime
dt = datetime.datetime.now()

In [29]:
dt

datetime.datetime(2015, 9, 28, 16, 19, 43, 958087)

In [34]:
print('{:%Y-%m-%d_%H:%M:%S}.json'.format(dt))

2015-09-28_16:19:43.json
